-- MySQL Script generated by MySQL Workbench
-- Thu Jan  4 13:12:47 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema moviequizdb
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `moviequizdb` ;

-- -----------------------------------------------------
-- Schema moviequizdb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `moviequizdb` DEFAULT CHARACTER SET utf8 ;
USE `moviequizdb` ;

-- -----------------------------------------------------
-- Table `moviequizdb`.`Parental_Rating`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `moviequizdb`.`Parental_Rating` ;

CREATE TABLE IF NOT EXISTS `moviequizdb`.`Parental_Rating` (
  `Parental_Rating_ID` INT UNIQUE NOT NULL AUTO_INCREMENT,
  `Title` VARCHAR(100) NOT NULL,
  `Description` VARCHAR(1000) NULL,
  `Age_Limit` SMALLINT NULL,
  `ModifiedBy` VARCHAR(45) NULL,
  `ModifiedOn` DATETIME NULL DEFAULT NOW(),
  PRIMARY KEY (`Parental_Rating_ID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `moviequizdb`.`Movie`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `moviequizdb`.`Movie` ;

CREATE TABLE IF NOT EXISTS `moviequizdb`.`Movie` (
  `MovieID` INT NOT NULL AUTO_INCREMENT,
  `Title` VARCHAR(100) NOT NULL,
  `Description` VARCHAR(1000) NULL,
  `Release_Date` DATETIME NULL,
  `Parental_Rating_ID` INT NULL,
  `Active` BIT(1) NULL DEFAULT 1,
  `ModifiedBy` VARCHAR(45) NULL,
  `ModifiedOn` DATETIME NULL DEFAULT NOW(),
  PRIMARY KEY (`MovieID`),
  INDEX `FK_Parental_Rating_idx` (`Parental_Rating_ID` ASC),
  CONSTRAINT `FK_Movie_Parental_Rating`
    FOREIGN KEY (`Parental_Rating_ID`)
    REFERENCES `moviequizdb`.`Parental_Rating` (`Parental_Rating_ID`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `moviequizdb`.`Genre`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `moviequizdb`.`Genre` ;

CREATE TABLE IF NOT EXISTS `moviequizdb`.`Genre` (
  `GenreID` INT UNIQUE NOT NULL AUTO_INCREMENT,
  `Title` VARCHAR(100) NOT NULL,
  `Description` VARCHAR(1000) NULL,
  `ModifiedBy` VARCHAR(45) NULL,
  `ModifiedOn` DATETIME NULL DEFAULT NOW(),
  PRIMARY KEY (`GenreID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `moviequizdb`.`Movie_Genre`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `moviequizdb`.`Movie_Genre` ;

CREATE TABLE IF NOT EXISTS `moviequizdb`.`Movie_Genre` (
  `Movie_Genre_ID` INT UNIQUE NOT NULL AUTO_INCREMENT,
  `MovieID` INT NOT NULL,
  `GenreID` INT NOT NULL,
  `ModifiedBy` VARCHAR(45) NULL,
  `ModifiedOn` DATETIME NULL DEFAULT NOW(),
  PRIMARY KEY (`Movie_Genre_ID`),
  INDEX `FK_Movie_idx` (`MovieID` ASC),
  INDEX `FK_Genre_idx` (`GenreID` ASC),
  CONSTRAINT `FK_Movie_Genre_Movie`
    FOREIGN KEY (`MovieID`)
    REFERENCES `moviequizdb`.`Movie` (`MovieID`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT `FK_Movie_Genre_Genre`
    FOREIGN KEY (`GenreID`)
    REFERENCES `moviequizdb`.`Genre` (`GenreID`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `moviequizdb`.`Game_Mode`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `moviequizdb`.`Game_Mode` ;

CREATE TABLE IF NOT EXISTS `moviequizdb`.`Game_Mode` (
  `Game_Mode_ID` INT UNIQUE NOT NULL AUTO_INCREMENT,
  `Title` VARCHAR(100) NOT NULL,
  `Description` VARCHAR(1000) NULL,
  `Type` VARCHAR(100) NULL,
  `Active` BIT(1) NULL DEFAULT 1,
  `ModifiedBy` VARCHAR(45) NULL,
  `ModifiedOn` DATETIME NULL DEFAULT NOW(),
  PRIMARY KEY (`Game_Mode_ID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `moviequizdb`.`Picture`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `moviequizdb`.`Picture` ;

CREATE TABLE IF NOT EXISTS `moviequizdb`.`Picture` (
  `PictureID` INT UNIQUE NOT NULL AUTO_INCREMENT,
  `Description` VARCHAR(1000) NULL,
  `Address` VARCHAR(400) NOT NULL,
  `ModifiedBy` VARCHAR(45) NULL,
  `ModifiedOn` DATETIME NULL DEFAULT NOW(),
  PRIMARY KEY (`PictureID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `moviequizdb`.`Country`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `moviequizdb`.`Country` ;

CREATE TABLE IF NOT EXISTS `moviequizdb`.`Country` (
  `CountryID` INT UNIQUE NOT NULL AUTO_INCREMENT,
  `Name` VARCHAR(150) NOT NULL,
  `Description` VARCHAR(1000) NULL,
  `Alpha2` VARCHAR(2) NULL,
  `Alpha3` VARCHAR(3) NULL,
  `ISO_Code` SMALLINT NULL,
  `ModifiedBy` VARCHAR(45) NULL,
  `ModifiedOn` DATETIME NULL DEFAULT NOW(),
  PRIMARY KEY (`CountryID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `moviequizdb`.`Language`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `moviequizdb`.`Language` ;

CREATE TABLE IF NOT EXISTS `moviequizdb`.`Language` (
  `LanguageID` INT UNIQUE NOT NULL AUTO_INCREMENT,
  `Title` VARCHAR(100) NOT NULL,
  `Description` VARCHAR(1000) NULL,
  `Abbr` VARCHAR(10) NULL,
  `Active` BIT(1) NULL DEFAULT 1,
  `ModifiedBy` VARCHAR(45) NULL,
  `ModifiedOn` DATETIME NULL DEFAULT NOW(),
  PRIMARY KEY (`LanguageID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `moviequizdb`.`User_Type`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `moviequizdb`.`User_Type` ;

CREATE TABLE IF NOT EXISTS `moviequizdb`.`User_Type` (
  `User_Type_ID` INT UNIQUE NOT NULL AUTO_INCREMENT,
  `Title` VARCHAR(100) NOT NULL,
  `Description` VARCHAR(1000) NULL,
  `Value` INT NULL,
  `ModifiedBy` VARCHAR(45) NULL,
  `ModifiedOn` DATETIME NULL DEFAULT NOW(),
  PRIMARY KEY (`User_Type_ID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `moviequizdb`.`User`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `moviequizdb`.`User` ;

CREATE TABLE IF NOT EXISTS `moviequizdb`.`User` (
  `UserID` INT UNIQUE NOT NULL AUTO_INCREMENT,
  `Name` VARCHAR(200) NOT NULL,
  `Birthday_Date` DATE NULL,
  `PictureID` INT NULL,
  `Username` VARCHAR(20) NOT NULL,
  `Password` VARCHAR(100) NOT NULL,
  `Email` VARCHAR(200) NULL,
  `Secondary_Email` VARCHAR(200) NULL,
  `Phone1` VARCHAR(30) NULL,
  `Phone2` VARCHAR(30) NULL,
  `CountryID` INT NULL,
  `LanguageID` INT NULL,
  `User_Type_ID` INT NOT NULL,
  `Gender` ENUM('M', 'F', 'O') NULL,
  `Subscription_Date` DATETIME NULL DEFAULT NOW(),
  `Active` BIT(1) NULL DEFAULT 1,
  `ModifiedBy` VARCHAR(45) NULL,
  `ModifiedOn` DATETIME NULL DEFAULT NOW(),
  PRIMARY KEY (`UserID`),
  INDEX `FK_Picture_idx` (`PictureID` ASC),
  INDEX `FK_Country_idx` (`CountryID` ASC),
  INDEX `FK_Language_idx` (`LanguageID` ASC),
  INDEX `FK_User_Type_idx` (`User_Type_ID` ASC),
  CONSTRAINT `FK_User_Picture`
    FOREIGN KEY (`PictureID`)
    REFERENCES `moviequizdb`.`Picture` (`PictureID`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT `FK_User_Country`
    FOREIGN KEY (`CountryID`)
    REFERENCES `moviequizdb`.`Country` (`CountryID`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT `FK_User_Language`
    FOREIGN KEY (`LanguageID`)
    REFERENCES `moviequizdb`.`Language` (`LanguageID`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT `FK_User_User_Type`
    FOREIGN KEY (`User_Type_ID`)
    REFERENCES `moviequizdb`.`User_Type` (`User_Type_ID`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `moviequizdb`.`Session`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `moviequizdb`.`Session` ;

CREATE TABLE IF NOT EXISTS `moviequizdb`.`Session` (
  `SessionID` INT UNIQUE NOT NULL AUTO_INCREMENT,
  `UserID` INT NOT NULL,
  `Start_Date` DATETIME NOT NULL,
  `End_Date` DATETIME NULL,
  `ModifiedBy` VARCHAR(45) NULL,
  `ModifiedOn` DATETIME NULL DEFAULT NOW(),
  PRIMARY KEY (`SessionID`),
  INDEX `FK_User_idx` (`UserID` ASC),
  CONSTRAINT `FK_Session_User`
    FOREIGN KEY (`UserID`)
    REFERENCES `moviequizdb`.`User` (`UserID`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `moviequizdb`.`Game_Session`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `moviequizdb`.`Game_Session` ;

CREATE TABLE IF NOT EXISTS `moviequizdb`.`Game_Session` (
  `Game_Session_ID` INT UNIQUE NOT NULL AUTO_INCREMENT,
  `SessionID` INT NOT NULL,
  `Start_Date` DATETIME NULL DEFAULT NOW(),
  `End_Date` DATETIME NULL,
  `Game_Mode_ID` INT NOT NULL,
  `Total_Score` FLOAT NULL DEFAULT 0,
  `ModifiedBy` VARCHAR(45) NULL,
  `ModifiedOn` DATETIME NULL DEFAULT NOW(),
  PRIMARY KEY (`Game_Session_ID`),
  INDEX `FK_Game_Mode_idx` (`Game_Mode_ID` ASC),
  INDEX `FK_Session_idx` (`SessionID` ASC),
  CONSTRAINT `FK_Game_Session_Session`
    FOREIGN KEY (`SessionID`)
    REFERENCES `moviequizdb`.`Session` (`SessionID`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT `FK_Game_Session_Game_Mode`
    FOREIGN KEY (`Game_Mode_ID`)
    REFERENCES `moviequizdb`.`Game_Mode` (`Game_Mode_ID`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `moviequizdb`.`Movie_Facts`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `moviequizdb`.`Movie_Facts` ;

CREATE TABLE IF NOT EXISTS `moviequizdb`.`Movie_Facts` (
  `Movie_Facts_ID` INT UNIQUE NOT NULL AUTO_INCREMENT,
  `MovieID` INT NOT NULL,
  `Title` VARCHAR(100) NOT NULL,
  `Description` VARCHAR(1000) NULL,
  `Date` DATETIME NULL DEFAULT NOW(),
  `Active` BIT(1) NULL DEFAULT 1,
  `ModifiedBy` VARCHAR(45) NULL,
  `ModifiedOn` DATETIME NULL DEFAULT NOW(),
  PRIMARY KEY (`Movie_Facts_ID`),
  INDEX `FK_Movie_Facts_Movie_idx` (`MovieID` ASC),
  CONSTRAINT `FK_Movie_Facts_Movie`
    FOREIGN KEY (`MovieID`)
    REFERENCES `moviequizdb`.`Movie` (`MovieID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `moviequizdb`.`Challenge`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `moviequizdb`.`Challenge` ;

CREATE TABLE IF NOT EXISTS `moviequizdb`.`Challenge` (
  `ChallengeID` INT UNIQUE NOT NULL AUTO_INCREMENT,
  `Start_Date` DATETIME NOT NULL DEFAULT NOW(),
  `End_Date` DATETIME NULL,
  `Winner_UserID` INT NULL,
  `Active` BIT(1) NULL DEFAULT 1,
  `ModifiedBy` VARCHAR(45) NULL,
  `ModifiedOn` DATETIME NULL DEFAULT NOW(),
  PRIMARY KEY (`ChallengeID`),
  INDEX `FK_Winner_User_idx` (`Winner_UserID` ASC),
  CONSTRAINT `FK_Challenge_User`
    FOREIGN KEY (`Winner_UserID`)
    REFERENCES `moviequizdb`.`User` (`UserID`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `moviequizdb`.`Player_Session_Challenge`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `moviequizdb`.`Player_Session_Challenge` ;

CREATE TABLE IF NOT EXISTS `moviequizdb`.`Player_Session_Challenge` (
  `Player_Session_Challenge_ID` INT UNIQUE NOT NULL AUTO_INCREMENT,
  `Game_Session_ID` INT NOT NULL,
  `ChallengeID` INT NOT NULL,
  `ModifiedBy` VARCHAR(45) NULL,
  `ModifiedOn` DATETIME NULL DEFAULT NOW(),
  PRIMARY KEY (`Player_Session_Challenge_ID`),
  INDEX `FK_Game_Session_idx` (`Game_Session_ID` ASC),
  INDEX `FK_Challenge_idx` (`ChallengeID` ASC),
  CONSTRAINT `FK_Player_Session_Challenge_Game_Session`
    FOREIGN KEY (`Game_Session_ID`)
    REFERENCES `moviequizdb`.`Game_Session` (`Game_Session_ID`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT `FK_Player_Session_Challenge_Challenge`
    FOREIGN KEY (`ChallengeID`)
    REFERENCES `moviequizdb`.`Challenge` (`ChallengeID`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `moviequizdb`.`Week_Movie`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `moviequizdb`.`Week_Movie` ;

CREATE TABLE IF NOT EXISTS `moviequizdb`.`Week_Movie` (
  `Week_Movie_ID` INT UNIQUE NOT NULL AUTO_INCREMENT,
  `Title` VARCHAR(100) NOT NULL,
  `Description` VARCHAR(1000) NULL,
  `MovieID` INT NOT NULL,
  `Start_Date` DATETIME NULL DEFAULT NOW(),
  `End_Date` DATETIME NULL,
  `Active` BIT(1) NULL DEFAULT 1,
  `ModifiedBy` VARCHAR(45) NULL,
  `ModifiedOn` DATETIME NULL DEFAULT NOW(),
  PRIMARY KEY (`Week_Movie_ID`),
  INDEX `FK_Movie_idx` (`MovieID` ASC),
  CONSTRAINT `FK_Week_Movie_Movie`
    FOREIGN KEY (`MovieID`)
    REFERENCES `moviequizdb`.`Movie` (`MovieID`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `moviequizdb`.`Week_Movie_Picture`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `moviequizdb`.`Week_Movie_Picture` ;

CREATE TABLE IF NOT EXISTS `moviequizdb`.`Week_Movie_Picture` (
  `Week_Movie_Picture_ID` INT UNIQUE NOT NULL AUTO_INCREMENT,
  `Week_Movie_ID` INT NOT NULL,
  `PictureID` INT NOT NULL,
  `ModifiedBy` VARCHAR(45) NULL,
  `ModifiedOn` DATETIME NULL DEFAULT NOW(),
  PRIMARY KEY (`Week_Movie_Picture_ID`),
  INDEX `FK_Week_Movie_idx` (`Week_Movie_ID` ASC),
  INDEX `FK_Picture_idx` (`PictureID` ASC),
  CONSTRAINT `FK_Week_Movie_Picture_Week_Movie`
    FOREIGN KEY (`Week_Movie_ID`)
    REFERENCES `moviequizdb`.`Week_Movie` (`Week_Movie_ID`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT `FK_Week_Movie_Picture_Picture`
    FOREIGN KEY (`PictureID`)
    REFERENCES `moviequizdb`.`Picture` (`PictureID`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `moviequizdb`.`Answer_Type`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `moviequizdb`.`Answer_Type` ;

CREATE TABLE IF NOT EXISTS `moviequizdb`.`Answer_Type` (
  `Answer_Type_ID` INT UNIQUE NOT NULL AUTO_INCREMENT,
  `Title` VARCHAR(100) NOT NULL,
  `Description` VARCHAR(1000) NULL,
  `ModifiedBy` VARCHAR(45) NULL,
  `ModifiedOn` DATETIME NULL DEFAULT NOW(),
  PRIMARY KEY (`Answer_Type_ID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `moviequizdb`.`Answer`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `moviequizdb`.`Answer` ;

CREATE TABLE IF NOT EXISTS `moviequizdb`.`Answer` (
  `AnswerID` INT UNIQUE NOT NULL AUTO_INCREMENT,
  `Title` VARCHAR(100) NOT NULL,
  `Answer_Type_ID` INT NOT NULL,
  `Value` INT NULL,
  `Active` BIT(1) NULL DEFAULT 1,
  `ModifiedBy` VARCHAR(45) NULL,
  `ModifiedOn` DATETIME NULL DEFAULT NOW(),
  PRIMARY KEY (`AnswerID`),
  INDEX `FK_Answer_Type_idx` (`Answer_Type_ID` ASC),
  CONSTRAINT `FK_Answer_Answer_Type`
    FOREIGN KEY (`Answer_Type_ID`)
    REFERENCES `moviequizdb`.`Answer_Type` (`Answer_Type_ID`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `moviequizdb`.`Question`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `moviequizdb`.`Question` ;

CREATE TABLE IF NOT EXISTS `moviequizdb`.`Question` (
  `QuestionID` INT UNIQUE NOT NULL AUTO_INCREMENT,
  `Question` VARCHAR(100) NOT NULL,
  `Description` VARCHAR(1000) NULL,
  `AnswerID` INT NOT NULL,
  `Source` VARCHAR(400) NULL,
  `Author_UserID` INT NULL,
  `Difficulty` SMALLINT NULL,
  `PictureID` INT NULL,
  `MovieID` INT NULL,
  `Active` BIT(1) NULL DEFAULT 1,
  `ModifiedBy` VARCHAR(45) NULL,
  `ModifiedOn` DATETIME NULL DEFAULT NOW(),
  PRIMARY KEY (`QuestionID`),
  INDEX `FK_Answer_idx` (`AnswerID` ASC),
  INDEX `FK_User_idx` (`Author_UserID` ASC),
  INDEX `FK_Picture_idx` (`PictureID` ASC),
  INDEX `FK_Movie_idx` (`MovieID` ASC),
  CONSTRAINT `FK_Question_Answer`
    FOREIGN KEY (`AnswerID`)
    REFERENCES `moviequizdb`.`Answer` (`AnswerID`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT `FK_Question_User`
    FOREIGN KEY (`Author_UserID`)
    REFERENCES `moviequizdb`.`User` (`UserID`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT `FK_Question_Picture`
    FOREIGN KEY (`PictureID`)
    REFERENCES `moviequizdb`.`Picture` (`PictureID`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT `FK_Question_Movie`
    FOREIGN KEY (`MovieID`)
    REFERENCES `moviequizdb`.`Movie` (`MovieID`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `moviequizdb`.`Game_Question`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `moviequizdb`.`Game_Question` ;

CREATE TABLE IF NOT EXISTS `moviequizdb`.`Game_Question` (
  `Game_Question_ID` INT UNIQUE NOT NULL AUTO_INCREMENT,
  `Game_Session_ID` INT NOT NULL,
  `QuestionID` INT NOT NULL,
  `Score` FLOAT NULL,
  `Answered_Time` FLOAT NULL,
  `ModifiedBy` VARCHAR(45) NULL,
  `ModifiedOn` DATETIME NULL DEFAULT NOW(),
  PRIMARY KEY (`Game_Question_ID`),
  INDEX `FK_Game_Session_idx` (`Game_Session_ID` ASC),
  INDEX `FK_Question_idx` (`QuestionID` ASC),
  CONSTRAINT `FK_Game_Question_Game_Session`
    FOREIGN KEY (`Game_Session_ID`)
    REFERENCES `moviequizdb`.`Game_Session` (`Game_Session_ID`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT `FK_Game_Question_Question`
    FOREIGN KEY (`QuestionID`)
    REFERENCES `moviequizdb`.`Question` (`QuestionID`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `moviequizdb`.`Movie_Facts_Picture`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `moviequizdb`.`Movie_Facts_Picture` ;

CREATE TABLE IF NOT EXISTS `moviequizdb`.`Movie_Facts_Picture` (
  `Movie_Facts_Picture_ID` INT UNIQUE NOT NULL AUTO_INCREMENT,
  `Movie_Facts_ID` INT NOT NULL,
  `PictureID` INT NOT NULL,
  `ModifiedBy` VARCHAR(45) NULL,
  `ModifiedOn` DATETIME NULL DEFAULT NOW(),
  PRIMARY KEY (`Movie_Facts_Picture_ID`),
  INDEX `FK_Movie_Facts_idx` (`Movie_Facts_ID` ASC),
  INDEX `FK_Picture_idx` (`PictureID` ASC),
  CONSTRAINT `FK_Movie_Facts_Picture_Movie_Facts`
    FOREIGN KEY (`Movie_Facts_ID`)
    REFERENCES `moviequizdb`.`Movie_Facts` (`Movie_Facts_ID`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT `FK_Movie_Facts_Picture_Picture`
    FOREIGN KEY (`PictureID`)
    REFERENCES `moviequizdb`.`Picture` (`PictureID`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `moviequizdb`.`Random_Mode`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `moviequizdb`.`Random_Mode` ;

CREATE TABLE IF NOT EXISTS `moviequizdb`.`Random_Mode` (
  `Random_Mode_ID` INT UNIQUE NOT NULL AUTO_INCREMENT,
  `Mode` VARCHAR(100) NOT NULL,
  `Description` VARCHAR(1000) NULL,
  `Value` INT NULL,
  `ModifiedBy` VARCHAR(45) NULL,
  `ModifiedOn` DATETIME NULL DEFAULT NOW(),
  PRIMARY KEY (`Random_Mode_ID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `moviequizdb`.`Random_Answer`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `moviequizdb`.`Random_Answer` ;

CREATE TABLE IF NOT EXISTS `moviequizdb`.`Random_Answer` (
  `Random_Answer_ID` INT UNIQUE NOT NULL AUTO_INCREMENT,
  `Random_Mode_ID` INT NOT NULL,
  `AnswerID` INT NOT NULL,
  `QuestionID` INT NULL,
  `Value` INT NULL,
  `Value2` INT NULL,
  `ModifiedBy` VARCHAR(45) NULL,
  `ModifiedOn` DATETIME NULL DEFAULT NOW(),
  PRIMARY KEY (`Random_Answer_ID`),
  INDEX `FK_Random_Answer_Random_idx` (`Random_Mode_ID` ASC),
  INDEX `FK_Random_Answer_Answer_idx` (`AnswerID` ASC),
  INDEX `FK_Random_Answer_Question_idx` (`QuestionID` ASC),
  CONSTRAINT `FK_Random_Answer_Random`
    FOREIGN KEY (`Random_Mode_ID`)
    REFERENCES `moviequizdb`.`Random_Mode` (`Random_Mode_ID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `FK_Random_Answer_Answer`
    FOREIGN KEY (`AnswerID`)
    REFERENCES `moviequizdb`.`Answer` (`AnswerID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `FK_Random_Answer_Question`
    FOREIGN KEY (`QuestionID`)
    REFERENCES `moviequizdb`.`Question` (`QuestionID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `moviequizdb`.`Hierarchy`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `moviequizdb`.`Hierarchy` ;

CREATE TABLE IF NOT EXISTS `moviequizdb`.`Hierarchy` (
  `HierarchyID` INT UNIQUE NOT NULL AUTO_INCREMENT,
  `Random_Mode_ID` INT NOT NULL,
  `Title` VARCHAR(100) NOT NULL,
  `Description` VARCHAR(1000) NULL,
  `Value` INT NOT NULL,
  `ModifiedBy` VARCHAR(45) NULL,
  `ModifiedOn` DATETIME NULL DEFAULT NOW(),
  PRIMARY KEY (`HierarchyID`),
  INDEX `FK_Hierarchy_Random_Mode_idx` (`Random_Mode_ID` ASC),
  CONSTRAINT `FK_Hierarchy_Random_Mode`
    FOREIGN KEY (`Random_Mode_ID`)
    REFERENCES `moviequizdb`.`Random_Mode` (`Random_Mode_ID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
